### ISSUE TITLE
Ilegal request serving vtiger docker behind https nginx server

### ISSUE THREAD

**Issue by mburger81** [javanile/vtiger-demo#3]
We used your docker-compose example to create a vtiger instance, if you expose the ports and go throughout localhost:8080 or ip:8080 anything is fine.

But we would like to run the instance behind https with hostname and valid ssl certificate. We use for this another nginx/letencrypt docker image.

But ofter login to vtiger we run into this error

![image](https://user-images.githubusercontent.com/3778892/64173500-bbd0a300-ce57-11e9-93bd-6e3d7c88a5c7.png)

We we click now on "indietro" we are on this vtiger home view, but we run into this error many times. Also on logout we run into this page

![image](https://user-images.githubusercontent.com/3778892/64173772-4a452480-ce58-11e9-8bf3-3479161e130c.png)

Having a look to vtiger and do your repsoistory we tried to set docker environment variable to 
`VT_SITE_URL=https://vtiger.myhostname.com`

But in this scenario we run into a loop.

Can you help?

**Comment by francescobianco** [comment]
@mburger81 try to create a file like this
https://github.com/javanile/vtiger-demo/blob/master/config_override.php
and mount on vtiger container in this way
https://github.com/javanile/vtiger-demo/blob/master/docker-compose.yml#L31

Give me any updates

**Comment by mburger81** [comment]
Thx a lot I have to try this tomorrow morning. But one question, is the override.php correct?
I'm really not a php expert but should the file not have a closing php tag? Or do I missing something?

**Comment by mburger81** [comment]
I did as you described but I got always the same error.

If I add `>` at the end of config_override.php I get this error
`Parse error: syntax error, unexpected '>' in /var/www/html/config_override.php on line 4`
So I know I mapped the file in the right way.

But without the > I have the same bug, so this is not resolving me the issue.

I'm using 443 port instead of 10443
  ```
nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - /srv/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /srv/docker/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    networks:
      - vtiger

vtiger:
    image: javanile/vtiger:7.1.0
    container_name: vtiger
    restart: always
    networks:
      - vtiger
      - mysql
    environment:
      - VT_DEBUG=true
      - VT_SITE_URL=https://localhost:443/
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '8080:80'
    volumes:
      - vtiger_app:/app
      - vtiger_logs:/var/www/html/logs
      - vtiger_storage:/var/www/html/storage
      - ./config_override.php:/var/www/html/config_override.php
    links:
      - mysql
```

Also I don't see any change in log using `VT_DEBUG=true` instead of default value
